/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var Slot1Occupied = false
		        var Slot2Occupied = false
		        var Slot3Occupied = false
		        var Slot4Occupied = false
		        var SystemOutOfService = false
		        var IOPortOccupied = false
		        var ReservedSlot = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name | starting...")
						 SystemOutOfService = false  
						forward("display_update", "display_update(working)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("working") { //this:State
					action { //it:State
						CommUtils.outblue("$name | waiting for load requests...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleLoadRequest",cond=whenRequest("load"))
					transition(edgeName="t01",targetState="handleSonarFail",cond=whenDispatch("sonar_fail"))
				}	 
				state("handleLoadRequest") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("load(CLIENT_ID)"), Term.createTerm("load(CLIENT_ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                // Check Out of Service or IOPort occupied
								                if (SystemOutOfService || IOPortOccupied) {
								answer("load", "retrylater", "retrylater(system_busy_or_out_of_service)"   )  
								
								                } else if (Slot1Occupied && Slot2Occupied && Slot3Occupied && Slot4Occupied) {
								answer("load", "reject", "reject(hold_full)"   )  
								
								                } else {
								                    // Find a free slot
								                    if (!Slot1Occupied) ReservedSlot = "slot1"
								                    else if (!Slot2Occupied) ReservedSlot = "slot2"
								                    else if (!Slot3Occupied) ReservedSlot = "slot3"
								                    else if (!Slot4Occupied) ReservedSlot = "slot4"
								CommUtils.outblue("$name | accepted request, reserved $ReservedSlot")
								answer("load", "reserved", "reserved($ReservedSlot)"   )  
								forward("led_cmd", "led_cmd(blink)" ,"led" ) 
								
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingForContainer", cond=doswitch() )
				}	 
				state("waitingForContainer") { //this:State
					action { //it:State
						CommUtils.outblue("$name | waiting for container at sensor area (30s timeout)...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_waitingForContainer", 
				 	 					  scope, context!!, "local_tout_"+name+"_waitingForContainer", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t02",targetState="handleTimeout",cond=whenTimeout("local_tout_"+name+"_waitingForContainer"))   
					transition(edgeName="t03",targetState="checkContainerArrival",cond=whenDispatch("sonar_data"))
					transition(edgeName="t04",targetState="handleSonarFail",cond=whenDispatch("sonar_fail"))
				}	 
				state("checkContainerArrival") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonar_data(D)"), Term.createTerm("sonar_data(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val DVal = payloadArg(0).toDouble()
								                // D < DFREE/2 simulates container presence
								                if (DVal < 10.0) { // e.g. DFREE is 20
								                    IOPortOccupied = true
								CommUtils.outblue("$name | container detected at IOPort sensor area")
								
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="robotExecution", cond=doswitchGuarded({ IOPortOccupied  
					}) )
					transition( edgeName="goto",targetState="waitingForContainer", cond=doswitchGuarded({! ( IOPortOccupied  
					) }) )
				}	 
				state("robotExecution") { //this:State
					action { //it:State
						CommUtils.outblue("$name | starting robot execution to load container into $ReservedSlot")
						request("move_robot", "move_robot(ioport)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="robotAtIOPort",cond=whenReply("move_done"))
				}	 
				state("robotAtIOPort") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("move_done(RESULT)"), Term.createTerm("move_done(success)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblue("$name | robot picked container at IOPort, moving to slot5")
						}
						request("move_robot", "move_robot(slot5)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="robotAtSlot5",cond=whenReply("move_done"))
				}	 
				state("robotAtSlot5") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("move_done(RESULT)"), Term.createTerm("move_done(success)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblue("$name | robot placed container at slot5, starting marker")
								forward("start_marking", "start_marking($ReservedSlot)" ,"marker" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="markingCompleted",cond=whenDispatch("marking_done"))
				}	 
				state("markingCompleted") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("marking_done(SLOT)"), Term.createTerm("marking_done(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblue("$name | container marking completed, moving to $ReservedSlot")
						}
						request("move_robot", "move_robot($ReservedSlot)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="robotAtReservedSlot",cond=whenReply("move_done"))
				}	 
				state("robotAtReservedSlot") { //this:State
					action { //it:State
						
						            if (ReservedSlot == "slot1") Slot1Occupied = true
						            else if (ReservedSlot == "slot2") Slot2Occupied = true
						            else if (ReservedSlot == "slot3") Slot3Occupied = true
						            else if (ReservedSlot == "slot4") Slot4Occupied = true
						            
						            IOPortOccupied = false
						            ReservedSlot = ""
						CommUtils.outblue("$name | robot placed container in reserved slot, returning HOME")
						forward("led_cmd", "led_cmd(off)" ,"led" ) 
						request("move_robot", "move_robot(home)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="robotExecutionCompleted",cond=whenReply("move_done"))
				}	 
				state("robotExecutionCompleted") { //this:State
					action { //it:State
						CommUtils.outblue("$name | container loaded successfully")
						forward("display_update", "display_update(working)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("handleTimeout") { //this:State
					action { //it:State
						CommUtils.outblue("$name | client timeout: disengaging...")
						forward("led_cmd", "led_cmd(off)" ,"led" ) 
						 ReservedSlot = ""  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("handleSonarFail") { //this:State
					action { //it:State
						CommUtils.outred("$name | sonar failure detected, system out of service!")
						 SystemOutOfService = true  
						forward("led_cmd", "led_cmd(off)" ,"led" ) 
						forward("display_update", "display_update(out_of_service)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="handleSonarRecovery",cond=whenDispatch("sonar_ok"))
					transition(edgeName="t011",targetState="handleLoadRequest",cond=whenRequest("load"))
				}	 
				state("handleSonarRecovery") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | sonar recovered, back to normal service")
						 SystemOutOfService = false  
						forward("display_update", "display_update(working)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
			}
		}
} 
