/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var Slot1Occupied = false
		        var Slot2Occupied = false
		        var Slot3Occupied = false
		        var Slot4Occupied = false
		        var SystemOutOfService = false
		        var IOPortOccupied = false
		        var ReservedSlot = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | starting...")
						 SystemOutOfService = false  
						forward("display_msg", "display_msg(service_working)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("working") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | waiting for load requests...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleLoadRequest",cond=whenRequest("load"))
					transition(edgeName="t01",targetState="handleDistanceLimit",cond=whenDispatch("distance"))
				}	 
				state("handleLoadRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("load(CLIENT_ID)"), Term.createTerm("load(CLIENT_ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                if (SystemOutOfService || IOPortOccupied) {
								answer("load", "retrylater", "retrylater(busy_or_out_of_service)"   )  
								
								                } else if (Slot1Occupied && Slot2Occupied && Slot3Occupied && Slot4Occupied) {
								answer("load", "reject", "reject(hold_full)"   )  
								
								                } else {
								                    if (!Slot1Occupied) ReservedSlot = "slot1"
								                    else if (!Slot2Occupied) ReservedSlot = "slot2"
								                    else if (!Slot3Occupied) ReservedSlot = "slot3"
								                    else if (!Slot4Occupied) ReservedSlot = "slot4"
								CommUtils.outblue("cargoservice | request accepted, reserved $ReservedSlot")
								answer("load", "reserved", "reserved($ReservedSlot)"   )  
								forward("led_state", "led_state(blink)" ,"led" ) 
								
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingForContainer", cond=doswitchGuarded({ ReservedSlot != ""  
					}) )
					transition( edgeName="goto",targetState="working", cond=doswitchGuarded({! ( ReservedSlot != ""  
					) }) )
				}	 
				state("waitingForContainer") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | waiting for container at IOPort sensor area...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_waitingForContainer", 
				 	 					  scope, context!!, "local_tout_"+name+"_waitingForContainer", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t02",targetState="handleTimeout",cond=whenTimeout("local_tout_"+name+"_waitingForContainer"))   
					transition(edgeName="t03",targetState="checkContainerArrival",cond=whenDispatch("distance"))
				}	 
				state("checkContainerArrival") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val DVal = payloadArg(0).toDouble()
								                // D < DFREE/2 to detect presence
								                if (DVal < 10.0) {
								                    IOPortOccupied = true
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="robotExecution", cond=doswitchGuarded({ IOPortOccupied  
					}) )
					transition( edgeName="goto",targetState="waitingForContainer", cond=doswitchGuarded({! ( IOPortOccupied  
					) }) )
				}	 
				state("robotExecution") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | using cargorobot to load container...")
						request("move_robot", "move_robot(ioport)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="robotAtIOPort",cond=whenReply("move_done"))
				}	 
				state("robotAtIOPort") { //this:State
					action { //it:State
						request("move_robot", "move_robot(slot5)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="robotAtSlot5",cond=whenReply("move_done"))
				}	 
				state("robotAtSlot5") { //this:State
					action { //it:State
						forward("start_marking", "start_marking($ReservedSlot)" ,"marker" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="markingCompleted",cond=whenDispatch("marking_done"))
				}	 
				state("markingCompleted") { //this:State
					action { //it:State
						request("move_robot", "move_robot($ReservedSlot)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="robotAtReservedSlot",cond=whenReply("move_done"))
				}	 
				state("robotAtReservedSlot") { //this:State
					action { //it:State
						
						            if (ReservedSlot == "slot1") Slot1Occupied = true
						            else if (ReservedSlot == "slot2") Slot2Occupied = true
						            else if (ReservedSlot == "slot3") Slot3Occupied = true
						            else if (ReservedSlot == "slot4") Slot4Occupied = true
						            
						            IOPortOccupied = false
						            ReservedSlot = ""
						forward("led_state", "led_state(off)" ,"led" ) 
						request("move_robot", "move_robot(home)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="robotExecutionCompleted",cond=whenReply("move_done"))
				}	 
				state("robotExecutionCompleted") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | container loaded successfully")
						forward("display_msg", "display_msg(service_working)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("handleTimeout") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | client timeout, disengaging...")
						forward("led_state", "led_state(off)" ,"led" ) 
						 ReservedSlot = ""  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitch() )
				}	 
				state("handleDistanceLimit") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val DVal = payloadArg(0).toDouble()
								                // D > DFREE for at least 3 secs simulates Out of Service
								                if (DVal > 20.0) {
								                    SystemOutOfService = true
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="handleOutOfService", cond=doswitchGuarded({ SystemOutOfService  
					}) )
					transition( edgeName="goto",targetState="working", cond=doswitchGuarded({! ( SystemOutOfService  
					) }) )
				}	 
				state("handleOutOfService") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | system out of service!")
						forward("led_state", "led_state(off)" ,"led" ) 
						forward("display_msg", "display_msg(out_of_service)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="checkRecovery",cond=whenDispatch("distance"))
					transition(edgeName="t010",targetState="handleLoadRequest",cond=whenRequest("load"))
				}	 
				state("checkRecovery") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val DVal = payloadArg(0).toDouble()
								                if (DVal <= 20.0) {
								                    SystemOutOfService = false
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="working", cond=doswitchGuarded({ !SystemOutOfService  
					}) )
					transition( edgeName="goto",targetState="handleOutOfService", cond=doswitchGuarded({! ( !SystemOutOfService  
					) }) )
				}	 
			}
		}
} 
