/* Generated by AN DISI Unibo */ 
package it.unibo.customer

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Customer ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("customer | pressing pushbutton to request load...")
						request("load", "load(client1)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t013",targetState="handleReserved",cond=whenReply("reserved"))
					transition(edgeName="t014",targetState="handleRetry",cond=whenReply("retrylater"))
					transition(edgeName="t015",targetState="handleReject",cond=whenReply("reject"))
				}	 
				state("handleReserved") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("reserved(SLOT)"), Term.createTerm("reserved(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Slot = payloadArg(0)  
								CommUtils.outmagenta("customer | request accepted, reserved slot: $Slot. Placing container...")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handleRetry") { //this:State
					action { //it:State
						CommUtils.outmagenta("customer | load request busy/retry later")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handleReject") { //this:State
					action { //it:State
						CommUtils.outmagenta("customer | load request rejected")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
